name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8
      - name: Check dependency compatibility
        run: |
          pip check
      - name: Run linter
        run: |
          flake8 *.py
      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          pytest tests/ -s
        timeout-minutes: 10
